### ISSUE TITLE
[RFC] Creating a master list for tags

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash-box#17]
Hello everyone! This is a long post, so hopefully I'm not overstepping my bounds here. I sent a rough pitch on how I thought tags could work to Stash (meaning the original developer) about a year ago. Basically, I shared the list of tags I use within my own personal, local database thinking it would be useful during development. Since work here seems to have become much less theoretical than those early days, I thought it could be worth sharing again.

(Also, my coding experience is extremely limited to the point of non-existence, so bear with me if I don't understand a lot of the more technical language or if I over-explain something.)

The premise I'm starting from is that for the tags contained in StashBox to be as useful and functional as possible, we should have a relatively static master list of possible tags. These tags should have clear definitions so both users and contributors know what everything means. Without a level of internal consistency to these tags, the accuracy and reliability of our data will suffer.

Stash saved and shared the outline/list/dictionary I sent him before. [You can find the whole thing here](https://gist.github.com/StashAppDev/cf71bd17cfd4397c16415155bf72fe07), but because it's so massive to the point of being embarrassing I'll give a brief synopsis as well so nobody feels like they have to scroll through all of it.

Because I have such a large list of tags, the only way to keep it manageable was to group everything together. I'm not sure how everybody feels about how tags should be structured and implemented, so for now it can just be seen as a convenient way of organizing my list so it can be more easily read and understood. I also can provide screenshots of my database in case anyone is curious what this system looks like in practice. I assure you it's much neater than the massive document above would imply.

## Synopsis
I have everything organized into three broad sections first, with smaller categories underneath each of them. 

**People Tags** contains tags that describe the appearance of a performer and may be listed on either a performer's individual profile page or to describe the appearance of performers within a particular scene. 
- Categories include *Age Group*, *Hair Color*, and *Height*. 
- Tags include *Teen*, *Blonde*, and *Petite*.

**Scene Tags** contains tags that describe the make-up of a particular scene/movie. 
- Categories include *Group Makeup*, *Relationship*, and *Location*. 
- Tags include *Couple*, *Girlfriend*, and *Classroom*.

**Actions** contains tags that describe actions in the scene. I only have two categories for these right now, *Acts* and *Finishers*. The first describes most positions and actions while the latter is reserved for finishing acts. (I'm trying to keep my language clean so GH doesn't get mad at me.) This is definitely the least fleshed out aspect of my list and I'm still not sure the best way to organize it. It contains a lot of modifiers with hyphens and just looks really ugly. Parent and sub-tags may help with this, I don't know.

## Approach
Because I've been actively using this list of tags myself for years now, I already have most commonly tagged aspects included with simple definitions for just about everything already. I've also designed it with a few key directions in mind as well. I'm sharing those thoughts here as a proposal for guiding principles to consider while finalizing our list of tags.
- *Try to keep the language as **inoffensive** as possible, using more neutral words for tags and definitions.*
I tried to avoid sounding cold and scientific, but I also want the language to be palatable for as broad an audience as possible, considering the subject matter. No need to turn people off because the default tag names are unnecessarily vulgar.
- *Allow for tags to be **additive**, erring on the side of inclusion.*
By "erring on the side of inclusion", I mean that if there's doubt over whether one tag should be used over another, it's probably best to use both. At the same time, tags are kept simple so that greater meaning can be achieved by combining them together. By following this system, we allow users to search for obscure aspects like, say, clothing that could be considered "business casual" by searching for scenes that contain both of the tags "Business Wear" + "Casual". This approach is closely related to my next rule of thumb...
- *Approach **subjective** tags as **objectively** as possible*.
For example, for a couple body part related categories (you can probably guess which) I have tags for essentially small, medium, and large. Where is the dividing line between these categories, meaning, when does small become medium? This is an inherently subjective decision to make, but I believe an important tag to keep track of. So why couldn't we just list both tags that could apply, listing "Small" and "Medium" at the same time? That way the scene/performer would not be excluded from searches that only include one or the other. If a user feels that our definitions are too broad (meaning the performers with an additional "Medium" tag no longer fit the "Small" tag they're also applied with) they can modify their search to include "Small" while excluding "Medium" to get a more narrowly defined set of results. This allows for more flexibility when describing edge cases, while still maintaining specificity so that the individual tags are still meaningful. This is the only way I can imagine making subjective tags workable if we imagine a shared database with a large number of people contributing tags. Rather than constantly debating which tag is more appropriate, consider the existence of a debate as an indication that *both* tags are likely appropriate. Everyone should be guided by the question, "Could a reasonable person consider this tag as fitting?" Or put another way, "Would a reasonable person be overly surprised to see this as a result when searching for that tag?" Additionally, the meaning of various subjective tags should become clearer the longer the system is used. If there's a question of if a tag fits, simply searching for that tag will provide plenty of examples of approved uses of that tag to compare it too.

## Possible Next Steps
As it stands, there are a lot of adjustments I feel could be made to my list. When considering it as a starting point for StashBox to use, the most glaring weakness is that it's too large. I should be able to cut the larger categories down to what I feel are the most common and most important tags without much trouble, so we can start with a much more manageable size, adding more as needed. 

If we decide that this is a worthwhile starting point and that my conception isn't way off base from where everybody else intends to take the tagging system, I thought the Wiki section on GitHub could be a good place to start. We could create a "Tag Dictionary" organized by the "Sections" and "Categories" described above and I could start loading them with the relevant tags and definitions from my list. If I go one category at a time, we can discuss the merits and flaws of each one, offer suggestions or replacements, consider alternatives, etc. either within this issue page or on Discord. This can serve as a reference document both for developers and users.

However people feel about my proposal, I would still be interested in helping flesh out this aspect of the project. Like I said before, I don't really have any coding knowledge so I'm pretty limited in what I can contribute to this project. Let me know what you think or if you have questions. I have the same username on Discord as well. I've been thinking about all of this stuff for a long time now, so I'm interested to hear which ideas people like, which don't make any sense, whether any of it conflicts with current plans, and more importantly what makes the most sense for incorporating into StashBox at this time.

**Comment by ghost** [comment]
First of all, it's great that you're thinking about this stuff. I haven't had a lot of time to think about how this can be managed, but I definitely think it's key to creating a useful data source. I'm currently working on backfilling tags to stashdb.org due to a screwup of my own making, and at last count it's 2.3M scene tags spread over 4144 unique tagnames, which is highly suboptimal.

Anyway, the only infrastructure we have currently is tags and tag aliases. The tag aliases are just redirects essentially so not super important. The idea is that when we start cleaning up, misspellings and synonyms will be merged and the "bad" tag is attached as an alias. There is no support for parent_tags, but we'll have to see if that's necessary. For instance it makes sense that MFF and FMM would be a subtag of threesome.

I'm a big fan of categories, I think that will add a lot of value to what is otherwise just a pile of text. It's also useful to be able to "extract" information about a scene based purely on the tags a user adds. There's no support for it currently but it should be straightforward to add. I'm picturing a flat list of categories with a "type" attached that will be either scene/performer/action/whatever.

You can see the list of tags I've scraped so far at https://stashdb.org/tags. This is going to be massively expanded tomorrow once I backfill. My first priority will be to deduplicate and par down that list, and to that effect it would be super useful if you're able to start on a tag dictionary that we could use to roughly sort things into. I don't think it's necessarily desirable to add too many tags all at once so a baseline of the most common and tags and categories would probably allow us to cover a good chunk of the tags, and then we could throw the rest in an "unsorted" category and deal with it later when we have a better idea of the direction.

I have some concerns about tags vs metadata for performer data, for instance breast size, tattoos, etc. which is already set on the performer and fully searchable that way, but we can handle that at a later point. In general, from a database and search perspective it's almost always better to have objective facts attached to the entity itself rather than a tag, but it requires a lot more work and thought, and for many things like scene setting it's probably not worth it.

Anyway, really great writeup, thanks!

**Comment by WithoutPants** [comment]
The evidence is mounting for some sort of parent tag or tag category concept.

In terms of next steps, I'm wondering if a more practical next step would be some sort of tag seed file that we can use, rather than a wiki page. It would provide an (opinionated) set of standard tags to add to a new stash-box instance that the administrator can choose to import (after modification if needed).

**Comment by AdultSun** [comment]
@WithoutPants 
I may have the terminology mixed up, but do you mean a seed file for StashApp? My conception is that the wiki we would develop would define the rules by which stashdb.org utilizes tags, including what the tags will be and what they are intended to describe. Would this seed file just allow individual users to import all of the "official" stashdb tags at once into their instance of StashApp? I think this would need to be an early step to make as well since the goal is to integrate the two, but I feel we would still need to discuss and decide what those tags should be first, as well as how they relate to each other. That's why I felt a wiki may be a more appropriate method to have that discussion, while creating an easily referenced and searchable resource moving forward. We could even create separate sections for "Proposed Tags" and "Approved Tags" in the wiki, moving them from one to the other as they are incorporated into stashdb.

I already have a smaller, prioritized list mostly finished for what I've referred to as People Tags and Scene Tags ("Actions" will take more work I think), complete with definitions and references to the tags currently included on stashdb. I'd just need access to a wiki to start posting the definitions for review. 

I should also explain while I'm thinking about it, I expect this process to influence how tags will be structured within the database (inheritance, sub-tags, etc.), so I feel it would be worth working out those details first before making too many changes on stashdb or individuals' personal StashApp databases. I can already tell that if we don't plan ahead about how to best convert the scraped tags that are already there to new "official" ones (while keeping those two types of tags separate somehow), we could end up either losing valuable data or muddying the database with inaccurate tags that will be difficult to clean up later. For example, the most basic tags just describing what "kind" of performers there are and how many of them are in a scene (think FM, FMM, FFM, FF, FFF, FFFF, etc.) are incredibly inconsistent in the current scraped data. (For instance, ["Couple"](https://stashdb.org/tags/Couple) is the closest scraped tag for an FM scene but actually includes a wide variety of combinations and orientations, including FF, MM, FFM, etc.) For this example as well as others, it would be impractical to attempt to convert all of these scraped tags to new similarly named "official" tags because we would be in-effect finalizing a lot of inaccurate data. We would have to use a more nuanced method of converting and adding tags, likely catered to each situation. *But*, we can't know what method will give us the most accurate data if we don't first establish what the final tag will be and what it will mean. How can you judge accuracy without a reference point?

I may be misunderstanding how StashApp, StashBox, StashDB and whatever other moving parts are meant to relate to each other, but my point is that working out these details first could save us a lot of time and effort in the long run.

**Comment by WithoutPants** [comment]
An instance of stash-box can have a collection of any tags. Someone might roll there own instance with a tag set completely different to what we do. It's up to the administrator how they manage those tags. What we're discussing here is for our official instance of stash-box (which for simplicity I'll refer as stashdb).

My proposal is an opinionated seed file that documents all of the required information that you are talking about. It would contain the tags and the tag hierarchy, along with a description for the tags. The reason for choosing a file rather than a wiki page is that the file is properly version controlled, and can have pull requests filed against changes, which can then be discussed etc. 

The seed file doesn't necessarily need to be a specific format at this point. Hell, the best idea might be just a markdown file that documents it. We can convert it to the appropriate format later.

I hope this is clear enough.

**Comment by laurus-lx** [comment]
For Actions - take a look at Sex Position Taxonomy on  [SexInfo101](https://sexinfo101.com/positions). There are 26 main categories (missionary, cowgirl, doggy style, etc), and each main category is further divided in to sub-categories (e.g. open missionary, wrapped missionary, etc.). They are extremely consistent, well organized and thorough - with 3d rendered illustrations.

**Comment by AdultSun** [comment]
@laurus-lx 
That is definitely a useful resource. I've just mentioned it on the project's Discord page for more feedback. We will probably need to customize their list a bit (particularly to consider other orientations and for multiple partners, everything seems geared for straight couples), but this will make a great starting point if we decide to include more specific positions like these in stash-box. Your point about markers is a good one too. That site's use of categories could fit nicely with the ability to list sub-tags under a marker's main tag in Stash. The recent addition of nested tags in the development branch of Stash makes it even more interesting. This gives me a lot to think about. Thank you for sharing!

**Comment by laurus-lx** [comment]
For anyone interested - sex position markers from SexInfo101 are available here (CSV/JSON + Images)
https://discord.com/channels/559159668438728723/893649454362656838

BTW, one thing I noticed about StashBox, is that it does not have images for tags. Having a reference image for positions is super useful, so hopefully tag images can be added.

**Comment by AdultSun** [comment]
Most of these ideas have already been implemented, should've been closed a long time ago.
