### ISSUE TITLE
[Feature] Add <abbr> or similar to tags when rendered

### ISSUE THREAD

**Issue by elizalabo** [stashapp/stash-box#454]
The industry uses a lot of acronyms which aren’t always immediately obvious. Most tags have descriptions that clarify their meaning. It would be useful if Stash rendered these descriptions using the `<abbr>` tag or similar.

Having this in place would make it easier to discern the meaning of unfamiliar tags by hovering over them. It’s also a big accessibility boost because screen-readers will read the `<abbr>` tag in full.

The `<abbr>` tag may not be the correct tag to use – it fulfils the function but isn’t strictly intended for this. JackStack suggests using the [`<title>` tag instead](https://discordapp.com/channels/559159668438728723/935611121371611157/1001378439292539011).

W3C [recommends using `<abbr>`](https://www.w3schools.com/tags/tag_acronym.asp) in place of the deprecated `<acronym>` tag.

The attached mockup is [by halorrr](https://discordapp.com/channels/559159668438728723/935611121371611157/1001296946964734045). It visually displays what I’m suggesting. (I removed the other tags from the image because I wasn’t sure their wording was safe for GitHub.)

![unknown](https://user-images.githubusercontent.com/109658323/180944570-97360a37-261f-45f7-8937-66ecba7e0074.png)

**Comment by scruffynerf** [comment]
Abbr is the correct solution... Tag titles are the chosen term for a concept, and not always the most common or well known term, or perhaps are, but someone only knows some other name for the idea... Since we often have tons of aliases behind a term, a quick way to see the meaning is needed and the abbr tag is meant to do that.

So +1 on using <abbr>
