### ISSUE TITLE
[Feature] Cosmetic navbar refactor

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash-box#512]
**Is your feature request related to a problem? Please describe.**
There's a litany of guidelines for StashDB but the link is (possibly) pinned somewhere in a Discord channel. This isn't an ideal location for a project that requires contributors to be versed with the docs. There should be a clear and obvious link to these documents front-and-center for end-users.

**Describe the solution you'd like**
Add a `Documentation` link to the menu bar.

**Additional context**
Adding a `Documentation` link starts to make the menu bar a bit crowded, but that can be easily solved because all-user specific menu items (Drafts, Logout, etc) should be consolidated into one group -- a user drop-down menu. See image below.

![stashdb](https://user-images.githubusercontent.com/37937507/192161163-5e701e31-e3cd-4610-af26-47627fcca2ea.png)

**Comment by Flashy78** [comment]
I previously added a link to the guidelines when I added the PR for displaying a warning when submitting a draft with no PHASH, but it was pointed out that stash-box is not StashDB specific, and so any link would need to be customizable by the admin somehow so that it isn't hardcoded to StashDB.
Maybe it should be a config file option or something?

**Comment by sleetx** [comment]
Can we bump up the priority on this? I'm seeing a lot of agreement in the chat about adding the guidelines to the main site. It should be very easy to find. The sooner this gets added, the sooner it can help reduce the burden of poorly submitted data.

**Comment by Flashy78** [comment]
I'm adding a `stash-box-config.yml` value for contributor guidelines url. Nothing will display on the UI if it is empty.

Unfortunately updating the main menu to relocate things to a dropdown is beyond my React abilities. So I was just going to add another item next to Drafts in the top header. I thought Contributor Guidelines made the most sense, but it's very long to add to the top header. I feel like even just Guidelines makes a bit more sense than Documentation, because it's not really about using StashDB, but more on what's required for submitting updates/edits.

**Comment by Flashy78** [comment]
Another thought I had was instead of the top header, have it show up a bit more prominently on the create/update pages for the different types of edits.

**Comment by Flashy78** [comment]
Or if the user has less than 100 accepted edits, give an extra message on the confirmation page asking them to ensure they're read the guidelines.

**Comment by echo6ix** [comment]
The inclusion of `Documentation` or `Docs` link in the sitewide header serves two important purposes I think. First, it ensures user familiarity as they may remain unaware of its existence until engaged in the manual submission process, if it only appears during editing. Secondly, the documentation itself can potentially extend beyond mere contribution guidelines to encompass broader site usage instructions, access requests, contact information for moderators, etc. Down the road as the site becomes more refined with more features, the Documentation can be moved into a sitewide header titled `Support`, and the documentation link can be placed in there with other support related items.

In order to enhance intuitiveness, I would propose grouping all non-user specific global items in the top header as they already are (sans the Drafts link), while consolidating user contextual items (such as drafts, logout, logged in as, etc.) within a dropdown menu titled with the user's username. This approach aligns with the intuitive design patterns employed by major platforms.
