### ISSUE TITLE
[RFC] Notify users of updated scenes/performers/edits

### ISSUE THREAD

**Issue by UltraHKR** [stashapp/stash-box#748]
*### Scope*
Notify users on login that certain scenes has been updated, for example I have submitted new scenes and metadata updates... I forget sometimes what I have done... (To not make the server burdensome we could limit it to submitted / accepted edits per user...)

*## Longer explanation and examples
I have submitted 49 updates in the last 14 days... 
(new scene, scene update, new performer, performer update, performer image addition.)

In total I have 311 edits, 12 cancelled, 15 rejected, 9 pending...
The new scenes unless I go back and search for them they're in limbo unless I check them against them...

For deleted scenes for example, I recently asked to delete 2 scenes which were lazy uploads with minimal metadata, the end user should be notified and the hashes should be merged not erased from the DB. 

And this also brings up the problem of massive performer image deletion...
Some user edits remove 5+ images and add and equal number of different images. Unless they were wrongly uploaded initially why is this accepted...

Some images should be harder to delete they should be sticky...

Which brings us to voting for a 2(+/-) year account I have voted 9! times...

**Comment by AdultSun** [comment]
For notifications on edits, we already have issue #284 to cover it. I've been told that much of this feature has been developed already but it has not been finished yet.

For notifications on updated scenes/performers, I believe that would be better handled on the Stash side. We have a comprehensive issue to track that one in the Stash repo already too: https://github.com/stashapp/stash/issues/2903

As for your other comments, many of them also have related issues for them already. Some may also be better handled as a guideline update for (I assume) StashDB instead of a software update, so feel free to discuss those in the **#ministry-of-truth** channel in our Discord.

I'm closing this issue since everything detailed here appears to be either a duplicate or out of scope for Stash-Box.
